### ISSUE TITLE
Spell container is not working correctly

### ISSUE THREAD

**Issue by DubhHerder** [DubhHerder/Prestidigitation_BG3#5]
The spell container `Target_Prestidigitation` adds the sub-spells(snuff, ignite and clean) to the character hotbar but they are added individually rather than grouped in the primary spell container

**Comment by FelipeRenault** [comment]
Since `Target_Prestidigitation` is deriving from `Target_Prestidigitation_Clean`, it has the property `data "SpellContainerID" "Target_Prestidigitation"`. I believe setting `data "SpellContainerID" ""` on the `Target_Prestidigitation` entry will solve this issue.
However, another way of fixing this is making `Target_Prestidigitation` hold the top level information, and make the other spells use the container. Most of the container spells are done that way, and I think it makes understanding the hierarchy better

**Comment by DubhHerder** [comment]
Thanks for this explanation. I understand the mistake now. 

I based the prestidigitation  entries on the entries for create and destroy water as it seemed to be the most similar surface effect management spell. The inverted hierarchy is a hold over from that as the spell-container `target_CreateDestoryWater` is derived from the sub-spell `Target_CreateWater` with the required `data "SpellContainerID" ""` rather than being top level itself. 

I must have removed the critical line when tidying up the code as I did not understand it's significance. Classic example of poor practice by altering existing code instead of starting fresh. 

I agree that making `Target_Prestidigitation` hold the top level information is a better solution and will resolve the issue that way to avoid further complications.

**Comment by FelipeRenault** [comment]
Unfortunately, you picked a bad example to start on. Earlier on EA, `Target_CreateWater` was a spell by itself, later on, badly converted into a spell container, given the necessity of having the "destroy" part incorporated as a separate spell. Even Larian fumbled on this occasion, forgetting the Staff of Rain, which now doesn't work properly, since it gives the `Target_CreateWater` and doesn't give the spell container for it. I hope they'll fix that, and while they don't, I partially fixed it in my mod.

Bad practices aside, I'm glad to help and I recommend always making the spell container higher in the hierarchy

**Comment by DubhHerder** [comment]
spell container issue is resolved
